### ISSUE TITLE
Installation of javabridge on Windows (ValueError: numpy.ndarray size changed error)

### ISSUE THREAD

**Issue by ElpadoCan** [SchmollerLab/Cell_ACDC#10]
Cell-ACDC on Windows automatically installs a pre-compiled version of  `javabridge` when you first launch the module "0. Create data structure from microscopy file(s)...". 

However, it doesn't seem to work on every Windows PC and you get the following error (see issue #9):

`ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

In this case, you need to install `javabridge` manually as follows:

1. Download and install Microsoft C++ Build Tools from [here](https://visualstudio.microsoft.com/visual-cpp-build-tools/). **IMPORTANT**: make sure to select **Desktop development with C++** when installing the C++ Build Tools. See screenshot below
2. Download and install **Java Development Kit** for Windows from [here](https://hmgubox2.helmholtz-muenchen.de/index.php/s/zocneD2j2wMwbNc). *Note: if you prefer to install Java directly from the Oracle website you can download it from [here](https://www.oracle.com/webapps/redirect/signon?nexturl=https://download.oracle.com/otn/java/jdk/8u311-b11/4d5417147a92418ea8b615e228bb6935/jdk-8u311-windows-x64.exe), but you will need to create an Oracle account*
3. If you do not have `git` you need to install it from [here](https://git-scm.com/download/win)
4. Open the Anaconda Prompt and activate the `acdc` environment
5. Uninstall `javabdridge` with the command `pip uninstall -y javabridge`
6. Install `javabdridge` with the command `pip install git+https://github.com/SchmollerLab/python-javabridge-acdc`

If you are still having issues, comment below, thanks!

**Visual Studio Build Tools installation:**

![visual_studio_settings](https://user-images.githubusercontent.com/55240925/156729565-34f67e2c-0aac-4674-9c0c-cb2fb314514e.png)

**Comment by jordanyx** [comment]
This solution worked for me, thank you!
