### ISSUE TITLE
"Create data structure from microscopy file" not working from GUI main menu

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#11]
**Describe the bug**
The button labeled "0: Create data structure from microscopy file(s)..." doesn't work when used from the small GUI window, but it works when using the "Launch Wizard" button from the larger Welcome window.

**To Reproduce**
1. Start CellACDC as normal.
2. In the GUI window, select option 0: Create data structure....
3. Follow prompts.

**Expected behavior**
Nothing happens in the actual folder where the image files are stored, and in the terminal the following line appears:
_"Checking if Java is installed...
Launching segmentation script...
Checking if Java is installed...
Done. If window asking to select a folder is not visible, it is behind some other open window.
15:10:52.498 [Thread-0] DEBUG loci.common.NIOByteBufferProvider - Using mapped byte buffer? false"_

The above appears if you choose to save in the same folder that the images are in. If selecting a different folder, I get this instead:
_"Checking if Java is installed...
Launching segmentation script...
Checking if Java is installed...
Done. If window asking to select a folder is not visible, it is behind some other open window.
Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\Lib\site-packages\cellacdc\dataStruct.py", line 549, in run
    self.progress.emit('Java VM running.')
RuntimeError: wrapped C/C++ object of type bioFormatsWorker has been deleted"_

Again, if you use the "Launch Wizard" button from the welcome window, the data prep can be done normally, even though all the prompts appear to be the same.

**Desktop (please complete the following information):**
 - Python version: Python 3.9
 - OS: Windows 10
 - Cell-ACDC v1.2.4

**Comment by ElpadoCan** [comment]
Hi Jordan, we had similar issues on macOS recently, which is the reason why we changed the way we open the Java Virtual Machine. It should be already fixed now. 

Are you using the developer version (i.e., you cloned with `git`)? If so, please pull the latest version. If you used GitHub Desktop click on the button on the top called "Fetch". You need to press it twice, first to fetch the changes and then to actually pull them. If you cloned with git on the terminal instead, open the terminal, navigate to the Cell_ACDC folder and use the command `git pull`. Let me know if that works.

**Comment by jordanyx** [comment]
Hi Francesco, I installed following the Anaconda instructions on the main page, and it says version 1.2.4rc2 in the Anaconda Prompt window when I run it. I haven't cloned the Git repository, so I don't think I'm using the developer version. Perhaps a silly question--when I install using _pip install cellacdc_, where does the actual code get installed? I don't see it in the directory from which I ran the command, but everything still opens when I do the usual thing (i.e. open Anaconda Prompt, activate the acdc environment, type command "acdc"). Maybe that would suggest some other way my installation is wonky?

**Comment by ElpadoCan** [comment]
Hi Jordan, no it's totally fine you installed the release version from PyPi, that's perfect. No need to clone then, I don't know why, I just supposed you might have had the developer version. 

Anyway, v1.2.4-rc.2 still had the issues with the Java Virtual Machine that you mentioned, but we released v1.2.4-rc3 in the last days and that version should have the fix. You can simply upgrade with the command `pip install --upgrade cellacdc` (after activating the environment). Also, no problem with v1.2.3 it cannot interfere.

For the folder where Cell-ACDC gets installed, it is the same folder as all other packages are installed, like numpy. It's a folder called `site-packages` inside the environment folder. You can see the path of all of your conda envs with the command `conda env list`. You can also see the path of Cell-ACDC when you go to the menu `Help --> About Cell-ACDC` from the main launcher. If you don't see it then it means I added that feature recently (I forgot which version has this feature). Another way to see the path is to run python in the terminal (after activating acdc env) then you type `import cellacdc`, press enter and type `cellacdc.__file__` and it will print the location of cellacdc. Let me know if it works

**Comment by jordanyx** [comment]
Hi Francesco, it worked after updating! I downloaded v.1.2.4rc2 on Wednesday, and didn't realize the bug was fixed in that short span. Thanks a lot, and I'll definitely try that first in the future!
