### ISSUE TITLE
Custom cellpose models support

### ISSUE THREAD

**Issue by dimethylglymaxim** [SchmollerLab/Cell_ACDC#126]
I propose to add a clear method of importing your own trained cellpose models.

**Comment by ElpadoCan** [comment]
Hi dimethylglymaxim, you are right I never thought of custom cellpose models, good suggestion! 

I will be on vacation for the next two weeks but I will definitely do it when I am back!

**Comment by dimethylglymaxim** [comment]
Woah, thanks) Looking forward to that. This whole project look SO PROMISING

**Comment by ElpadoCan** [comment]
Hi @dimethylglymaxim, I just released Cell-ACDC `v1.2.4rc35` with custom cellpose models. In the models dialogue, you can now choose the model called `cellpose_custom` and you will get the same parameters as cellpose except for the model name where you will have to insert a path to your custom model. 

Please, upgrade with the command `pip install --upgrade cellacdc` (after activating the env). 

Since I don't have a custom cellpose model I could not test it, so let me know if it works, thanks!

**Comment by dimethylglymaxim** [comment]
Hello @ElpadoCan thank you for your work. I tried to test it, and it doesn't work, unfortunately. After selecting all the parameters for custom cellpose model, I get this in the console:

Initializing Segmentation module v1.2.4rc35...
Loading data...
Importing cellpose_custom...

Processing Y:/Data/VPs/Position_1/Images
-----------------------------------------
Loading Position_1\Images\vp=1_s01_visible_aligned.npz...
-----------------------------------------
Segmentation file vp=1_s01_segm_1.npz...
Traceback (most recent call last):
  File "C:\Users\Username\Miniconda3\lib\site-packages\cellacdc\segm.py", line 249, in run
-----------------------------------------    lab = self.model.segment(img, **self.segment2D_kwargs)

Image shape = (10, 1862, 1455)
  File "C:\Users\Username\Miniconda3\Lib\site-packages\cellacdc\models\cellpose_custom\acdcSegment.py", line 25, in segment
-----------------------------------------
labels = self.cp.model.segment(Segmenting with cellpose_custom...

AttributeError: 'CellposeModel' object has no attribute 'segment'

**Comment by ElpadoCan** [comment]
Ok, thanks for reporting this. Since I don't have a custom model to test with I didn't get that far. 

Could you please share the custom cellpose model that you are using? You can send it to my Google drive account padovaf@tcd.ie or with any other method that you prefer, thanks!

**Comment by ElpadoCan** [comment]
Thank you very much for sending me the model, it was very helpful!

I released `v1.2.4rc36` which should have the fix. Please update with `pip install --upgrade cellacdc` and let me know if it works, thanks!

**Comment by dimethylglymaxim** [comment]
Thank you, everything works as intended!
