### ISSUE TITLE
Autosave functon

### ISSUE THREAD

**Issue by Ciro1990** [SchmollerLab/Cell_ACDC#131]
Hi Francesco! 

I would like to suggest a new feature: the autosave.

I think it could be very useful when segmenting time-lapse. It would be a good idea just to update the mask file, without metrocs (so it is faster). 

Hope this can be implemented.

Ciro

**Comment by ElpadoCan** [comment]
Hi Ciro,

Sure that will be easy to implement. I was thinking to allow the user to choose how often it should save, what do you think? Another possibility is that it saves a temporary file (in the background) for every edit you do and then when you reopen Cell-ACDC it will detect if the temporary file is different from the saved file and it would ask you if you want to restore the temporary file?

**Comment by Ciro1990** [comment]
The idea of the temporary file sounds perfect, I think it would fulfill most of the users' needs. Definitely worth to try!

**Comment by ElpadoCan** [comment]
Hi Ciro, I implemented the autosaving function. It should save the segmentation masks and the annotations to a `.recovery` folder inside the Position folder every time you edit something. When you actually save yourself, this folder is deleted. 

When you open Cell-ACDC it will detect if the recovery folder is present and it will ask you if you want to load data from that folder instead. 

You can turn off autosaving from the menu on the top menu bar `File --> Autosave`.

Let me know if it works, thanks!

**Comment by Ciro1990** [comment]
Hi Francesco, 

I tried the new function and it works perfectly! 

Thanks for implementing it!
Ciro

**Comment by ElpadoCan** [comment]
Closing because we released this function starting from Cell-ACDC v1.2.4rc35
