### ISSUE TITLE
Installing yeastmate

### ISSUE THREAD

**Issue by lostinwild** [SchmollerLab/Cell_ACDC#132]
Hi Francesco,

Its Gaurav again. I was having issues installing 'yeastmate' package, please find the screenshot attached for troubleshooting. I am not sure if its a problem at my end..
![Yeastmate_installing issue](https://user-images.githubusercontent.com/78084008/186582815-dd6604be-55a5-408a-a3df-b36596d171cd.png)

Also, on using `pip install yeastmate` i get the following error
ERROR: Could not find a version that satisfies the requirement yeastmate (from versions: none)
ERROR: No matching distribution found for yeastmate

Also, for some reason i m unable to find the Jupiter notebook that we can use for analysis..

Thankyou for your time
Gaurav

**Comment by ElpadoCan** [comment]
Hi Gaurav, could you please try the command `pip install "git+https://github.com/hoerlteam/YeastMate"`? Let me know if it works, thanks!

**Comment by lostinwild** [comment]
Thank-you, it works! 
I have one more doubt, how do i locate the juptyer notebook. I have the juptyer notebook installed but i am unable to locate the analysis notebook..

**Comment by ElpadoCan** [comment]
Great! For the notebooks you find them here https://github.com/SchmollerLab/Cell_ACDC/tree/main/notebooks

**Comment by ElpadoCan** [comment]
Hi @lostinwild I am closing this because it sounds like you solved your issue. Feel free to reopen this issue or create a new one! Cheers
