### ISSUE TITLE
Enable downstream analysis for symmetric cell division

### ISSUE THREAD

**Issue by Beno71** [SchmollerLab/Cell_ACDC#133]
As discussed with @Ciro1990, we can use the columns describing symmetric cell division in acdc output data to analyse traits specific to symmetric cell division in the downstream analysis notebook.

First examples:
- Correlation of cell size at birth with cell cycle length
- Correlation of growth in first x minutes after birth with cell cycle length

**Comment by ElpadoCan** [comment]
To facilitate plotting the lineage tree I added a new column called `root_ID_tree`. This is the cell ID at the top of each tree. Grouping by `root_ID_tree` allows for plotting and/or analysing one tree at the time.

**Comment by Beno71** [comment]
I implemented two plots on your test data, @Ciro1990!
File selection works just as before but I implemented a small helper function to simply load the output created by ACDC instead of providing the possibility to re-calculate metrics in the notebook. We will change this in the future anyways and base the downstream notebook solely on the output csv.

First plot shows cell area at birth vs. length of the following cell cycle. Feel free to exchange this with volumes if needed.
For the second plot I calculated a sliding average of areas with a window size of 3 to account for noise in the segmentation labels and then subtracted the average area on the first 3 frames from the area on frames 9-11 after division. That should be a robust indicator for the growth after cell birth.

Let me know if this does the job for now and helps in further looking into the downstream analysis of your data!

**Comment by Ciro1990** [comment]
Hi Beno,

Thanks a lot for the updated notebook! I have tried it and everything works up until the "Distribution of cell cycle length". I am attaching a screenshot of the error here: 

![image](https://user-images.githubusercontent.com/96627336/187624729-a139f606-4af1-40ef-9e7a-5253b8f54710.png)

Ciro

**Comment by Beno71** [comment]
Hi Ciro, 
I was not aware that you also want to use the existing plots. Those are calculated on columns describing asymmetric cell division and could be non-sense on your data for that reason.
The distribution of cell cycle length could be calculated from the aggregations that I now performed to correlate cell size at birth and cell cycle lengths. I can add the distribution of cell cycle length for symmetrically dividing cells.
Also feel free to write down further suggestions in another ticket and I will add them!

**Comment by Ciro1990** [comment]
Thanks, Beno. Absolutely, If I can think about new parameters to be calculated, I will open a new thread.
