### ISSUE TITLE
Segmentation ids get lost usually on last frame during retracking

### ISSUE THREAD

**Issue by lostinwild** [SchmollerLab/Cell_ACDC#135]
[2022-08-30_03-54-55_segm_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/9449336/2022-08-30_03-54-55_segm_stdout.log)
**Describe the bug**
Segmentation ids disappear usually if doing retracking multiple time. Always happens on the last frame of my time-series data

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Python version: [e.g. Python 3.9]
 - OS: [e.g. Windows 10]
 - Cell-ACDC Version [e.g. v1.2.4, you can find this from the menu "Help-->About Cell-ACDC" on the main Launcher]

**Additional context**

**Comment by ElpadoCan** [comment]
Hi @lostinwild, I see you are using Bayesian Tracker with YeaZ can I ask why? YeaZ is for yeast cells while the Bayesian Tracker is more for symmetrically dividing mammalian cells.

If the tracking is not correct then it is the Bayesian Tracker's fault, and for that you would need to ask the developers of btrack about how to tune the parameters for your use case.

This is btrack github page https://github.com/quantumjot/BayesianTracker

**Comment by lostinwild** [comment]
Hi Francesco 
Thankyou for your quick reply. I was using it simply because it was working fine for the most part. For some reason, with  yeaz or cell acdc tracking, my cell-ids don't increment properly. For example, in the image attached below, after cell 4, next id should be '5' instead of '17'....i have tried re-initializing the tracking from start but  nothing works...am i missing something?
![image](https://user-images.githubusercontent.com/78084008/187408832-6c2e13cd-13fc-418d-928c-5df67ffb3e8f.png)

**Comment by ElpadoCan** [comment]
Oh ok, now I get your problem. Having non-sequential IDs is usually the same as sequential IDs. An ID is just a number it doesn't matter what number it is. That bud can be ID 17; as long as it stays 17 there should be no problem. 

However, if you need sequential IDs there is a dedicated function in Cell-ACDC. You can find it in the top menu bar at the menu `Segmentation --> Relabel IDs sequentially...` (shortcut is `Ctrl+L`). 

You can run this function before or after checking tracking and segmentation, I recommend running it after. Let me know if it works.

PS: The reason why that bud has ID 17 is that new objects get a new ID that is unique throughout the whole video. This is important to ensure the uniqueness of tracked IDs.

**Comment by lostinwild** [comment]
Thankyou so much, that's what we were looking for...it works. For time-point data, i have relabel function (ctrl+L) on the last frame and then everything is labeled sequentially starting from the first frame
