### ISSUE TITLE
Proposition to add "Load last selection..." for all checkboxes in Set measurments window

### ISSUE THREAD

**Issue by dimethylglymaxim** [SchmollerLab/Cell_ACDC#145]
Just a nice little quality of life feature, I think. 
![image](https://user-images.githubusercontent.com/111124664/189620479-e20853c9-8c8e-4488-a54d-8ba45a5939fd.png)
You can see, that in my case I have to press "Load last selection..." 8 times, so I think that "optimization" is worth it.

**Comment by ElpadoCan** [comment]
Hi @dimethylglymaxim I just released `v1.2.4rc39` where you will find a global "Load last selection..." button at the bottom of the set measurements window. To update, activate the environment and then use the command `pip install --upgrade cellacdc`. Let me know if it works, thanks!
