### ISSUE TITLE
Set measurements window does not work as intended

### ISSUE THREAD

**Issue by dimethylglymaxim** [SchmollerLab/Cell_ACDC#146]
It does not matter which checkboxes you check in that window - you will always get all of the measurements in acdc_output file.

Steps to reproduce:
1. Go to "Set measurements";
2. Deselect any measurements;
3. Close window by pressing "Ok";
4. Save file or check "Set measurements" window again.

It is expected, I believe, to exclude some measurements from acdc_output file by performing steps above.

 - Python version: Python 3.9.12
 - OS: Windows 10
 - Cell-ACDC Version: 1.2.4rc36
 
 P.s. 
 It worked, somehow. I have to test it more.

**Comment by ElpadoCan** [comment]
Hi @dimethylglymaxim, another user reported similar issues for some older versions but in the latest it should have been fixed. Note that if you uncheck a measurement that was already saved you need to confirm that you actually want to remove it and it will be removed only when you save the metrics. Do not hesitate to reopen the issue if it doesn't work for you, thanks!
