### ISSUE TITLE
Scroll bar sometimes scrambles masks

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#149]
Version: CellACDC 1.2.4rc38
Windows 10
Python 3.9.12

Sometimes in seg/track mode when I scroll back and forth using the scroll bar, the masks get messed up. I'm not sure exactly how to reproduce it but it seems to involve using the mouse to scroll between frames. The below image has the masks of the last frame replace that of the first frame.

![error](https://user-images.githubusercontent.com/99368623/190501897-fb26764d-0d5d-4221-a244-001777175612.PNG)

**Comment by ElpadoCan** [comment]
Hi Jordan, wow that looks very wrong :D

Can you tell if they are screwed up also upon saving, or is it just a visualization error? Does it happen often? Is there any error in the terminal? What happens when you then go to frame 2? Does it show frame 1, is it stuck at the last frame or does it show the correct frame? Thanks!

**Comment by jordanyx** [comment]
Hi Francesco,

I've run into the problem multiple times within a few minutes, so it happens with a reasonably high frequency (maybe due to my particular use habits, not sure). It sometimes happens with arrow keys too, not just scroll bar, and I think there's some correlation with scrolling quickly or holding the arrow keys down without stopping? Not certain, it's not regular.

It seems the mask for that frame gets entirely replaced; it's still there when I save and load again, and the frames before and after don't seem affected (i.e. if I go to the next frame, that one is fine). The bad mask stays in viewer mode too. I didn't get any errors in Terminal, but maybe it got buried by subsequent scrolling; I'll keep an eye out for the next time it happens.

**Comment by ElpadoCan** [comment]
Hi Jordan,

Thank you for answering, I have never seen that behaviour before, but I will now try different combinations of arrow keys and scrolling. As soon as I can trigger it I will fix it immediately. I keep you updated, thanks! 

Cheers,
Francesco

**Comment by jordanyx** [comment]
So it happened again, and I've confirmed nothing shows up in terminal. This time what triggered it was advancing from frame 1 to frame 2, then going back again. I closed without saving, but when I reopened it was still there, which was quite surprising. I wonder if it has something to do with the autosave feature? I deactivated it partway through the latest position, because the autosave has been giving me other issues like problems with the saving. I will make an issue for that once I find something concrete and reproducible.

**Comment by jordanyx** [comment]
I figured out a way to reproduce it! If I use Ctrl-S to quick-save, and then use arrow keys to advance, it replaces whatever mask I was on with the last frame mask. It seems to only happen with the keyboard shortcut, as opposed to using the save button at the top.

**Comment by jordanyx** [comment]
Sorry about the many comments--I also just confirmed it happens even if I use ctrl-S in cycle analysis mode, where masks aren't normally edited.

**Comment by ElpadoCan** [comment]
Thank you very much for spotting that! I will fix it immediately, thank you for your patience!

**Comment by ElpadoCan** [comment]
Hi Jordan, I just released `v1.2.4rc39` with a fix for this issue. Please update with `pip install --upgrade cellacdc`.

Thank you very much for finding the way to replicate it because it took me 2 seconds to fix!

**Comment by jordanyx** [comment]
Hi Francesco, looks like it's fine now. Thanks for the fix!!
