### ISSUE TITLE
Module 0 not working with multichannel tif hyperstack

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#15]
**Describe the bug**
Data structure not created properly when using a tif hyperstack. Not sure if it's because of the particular tif structure or because of ACDC, so wanted to check. Test tif file included at this Google drive link: https://drive.google.com/file/d/1NunHk991rXsczrw7tW1rep_PhiltA8jV/view?usp=sharing

**To Reproduce**
1. Starting from many individual tif files (one per time frame and channel), use FIJI to construct a hyperstack where one channel is Phase, one is fluorescence (for example). Final dimensions: 121 time frames, 2 channels (phase and fluo), 1 z stack.
2. Open CellACDC.
3. Open Module 0.
4. Load tif. Metadata window correctly previews phase and fluo channels as separate.
5. Run Module 0.
6. Open GUI and load position; for some reason, both channels become the fluo, so there's no phase. Checking in FIJI confirms that the two tifs saved in the position folder are both for the fluo channel, so the Phase is never saved as a tif.

**Expected behavior**
When loading a .zvi, this issue doesn't happen; each channel is saved separately as a .tif in the "Position_X" folder, and loads into the GUI accordingly.

**Desktop (please complete the following information):**
 - Python 3.9.7
 - OS: Windows 10
 - Cell-ACDC v1.2.4rc4

**Comment by ElpadoCan** [comment]
Hi Jordan, thanks for reporting this, I fixed it, but if you don't mind I would wait to implement also the other features that you requested (about the metrics) before releasing. It should take a week, is that ok? If you need the fix immediately I can release it earlier, let me know, thanks

**Comment by jordanyx** [comment]
Hi Francesco, I would actually like to use it as soon as possible if it's not too much trouble to just release that fix. But if that would cause problems I can wait a week. Looking forward to the new features!

**Comment by ElpadoCan** [comment]
Sure no problem, I will release on Monday then!

In the meantime (and in general when you have problems with module 0) since you are already using Fiji you can always generate the required data structure manually using Fiji. There is a section in the manual called "**Manually create data structure from microscopy file(s)**" that will guide you through that process. If you try it let me know if it works or you think some parts are not clear.

**Comment by ElpadoCan** [comment]
Hi Jordan, I published the release. Activate the environment and run the command `pip install --upgrade cellacdc` to get the latest version. Let me know if it works, thanks!

**Comment by jordanyx** [comment]
Hi Francesco, the update worked perfectly! Thanks so much, saves me a lot of time from doing the data structures manually.
