### ISSUE TITLE
Add "Apply to all future frames" including non-visited frames

### ISSUE THREAD

**Issue by ElpadoCan** [SchmollerLab/Cell_ACDC#158]
Add "Apply to all future frames" including non-visited frames:

- Rename "Apply to all future frames" to "Apply to all VISITED frames (recommended)"
- Add "Apply to all future frames"

**Comment by ElpadoCan** [comment]
Changes that are propagated (hence will require testing):

- Delete ID
- Edit ID
- Exclude cell from analysis
- Annotate cell as dead

**Comment by Beno71** [comment]
I tested this in combination with "Remember my choice and do not show this message again"
On the initial cell I deleted, it worked but later I deleted some cells which were then not deleted on all future frames

**Comment by ElpadoCan** [comment]
I'm closing this because it seems to be working now.
