### ISSUE TITLE
Error window keeps showing up

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#17]
**Describe the bug**
Error window pops up repeatedly; not sure what the cause is.

**To Reproduce**
Was using GUI like normal; tried editing a cell and this happened. Not sure how to reproduce, but every time I go to the same frame to make an edit it pops up. Seems to mainly happen when using the "segmentation mask overlay" option for the lefthand GUI, but haven't figured out exactly how to trigger it consistently.

**Screenshots**
See screenshot below.

**Desktop (please complete the following information):**
 - Python 3.9.7
 - OS: Windows 10
 - Cell-ACDC v1.2.4rc5

**Additional context**
![popup](https://user-images.githubusercontent.com/99368623/159092637-f873d0f0-58d5-43ed-a11f-327e4c3a5cd9.PNG)
[2022-03-18_15-24-16_gui_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/8307953/2022-03-18_15-24-16_gui_stdout.log)

Under "Show Details" in the popup:
"Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 117, in inner_function
    result = func(self, *args, **kwargs)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 10569, in updateALLimg
    img = self.overlaySegmMasks(img)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 9865, in overlaySegmMasks
    colors = [posData.lut[ID]/255 for ID in posData.IDs]
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 9865, in <listcomp>
    colors = [posData.lut[ID]/255 for ID in posData.IDs]
IndexError: index 276 is out of bounds for axis 0 with size 276
"

**Comment by ElpadoCan** [comment]
Hi Jordan, I just tried with one of my datasets and I cannot trigger that error, could you please send me the position that is causing the error? Thanks

**Comment by ElpadoCan** [comment]
It turns out that I actually thought that exact situation could happen, but the logic I used to prevent it doesn't work. I will fix it today. I let you know when you can update, thanks!

**Comment by ElpadoCan** [comment]
Ok, I just released a possible fix, but since I don't have a dataset that triggers that error I cannot test if the fix works. Update cellacdc with the command `pip install --upgrade cellacdc`. If doesn't work, please upload the Position that triggers the error, if possible of course, but I think it should work now. If it works I don't need your dataset of course. Cheers, Francesco

**Comment by jordanyx** [comment]
Hi Francesco, unfortunately updating didn't work. It seems to happen with every position, and I think it triggers when I have the segmentation overlay on and try to use the brush or erase tools. When I hit "OK" from the error window and use arrow keys or the bar to change frames, the frame number changes but the display doesn't, until I change the GUI option to "contours" or something else. I've gone back to editing using "contours only" for now. If it helps, here's one of the positions I saw the problem with: https://drive.google.com/file/d/1NunHk991rXsczrw7tW1rep_PhiltA8jV/view?usp=sharing

**Comment by ElpadoCan** [comment]
Hi Jordan, so I segmented and manually corrected the whole video you provided and I cannot trigger that error. Could you please zip the entire position folder and send it to me, if possible? Thanks!

**Comment by jordanyx** [comment]
Hi Francesco, the link to the file is here: https://drive.google.com/file/d/1p5FjzlgUST1FMeKRhnfWbhX0KR4P2rZu/view?usp=sharing

All I have to do to trigger the error is load this position in the GUI, switch to mask overlays, then try using the brush or eraser tool and change frames with arrow keys. Hope this helps!

**Comment by ElpadoCan** [comment]
Hi Jordan, I just released `v1.2.4rc7` that contains the fix for this. 

Update with `pip install --upgrade cellacdc` and let me know if it works, thanks!

**Comment by ElpadoCan** [comment]
Something I forgot to mention, while working on your data I realised that you probably don't know about a feature called `Relabel IDs sequentially...`. You can find this function from menu `Segment` or you can trigger it with `Ctrl+L`. This function will relabel all the IDs so that they are sequential 1, 2, 3, etc. and it will also adjust any cell cycle annotation accordingly. It might be handy to use at the end to avoid those big cell IDs that you have.

**Comment by jordanyx** [comment]
Hi Francesco, I'm not getting the error anymore, so looks like it's fixed! Thanks, this makes the manual corrections a lot easier.

Thanks for the heads-up about sequential relabeling! I had missed that earlier, and it does make things simpler.
