### ISSUE TITLE
A way to toggle right click colormap menu

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#18]
**Is your feature request related to a problem? Please describe.**
When using the GUI to edit masks, I like to have my cursor on the left side because when editing a cell it shows the pixel mask overlaid with the phase image. But when I use certain shortcut tools (e.g. "s" to separate cells) and then right click, the colormap selection menu pops up, which gets in the away, and clicking away from it sometimes leads to me accidentally drawing or erasing where I didn't mean to because the underlying tool is still active on my cursor. This doesn't happen if I do the right click on the right side of the GUI at least, but I like being able to do all my modifications on the side with the phase overlay.

**Describe the solution you'd like**
It would be nice if the colormap menu that pops up on a right click could be moved somewhere else so that it doesn't get in the way of using the right-click tools on the GUI's left side. Alternatively, perhaps that menu could be made to not pop up unless there's no active tool on the cursor?

This is a pretty minor quality of life thing, but would be nice to have!

**Comment by ElpadoCan** [comment]
Hi Jordan, I just released `v1.2.4rc7` that contains the fix for this. Update with `pip install --upgrade cellacdc` and let me know if it works, thanks!

**Comment by jordanyx** [comment]
Hi Francesco, this works fine for me now! Thanks!
