### ISSUE TITLE
Error Message: gui_mouseReleaseEventImg1

### ISSUE THREAD

**Issue by jacobmhkim** [SchmollerLab/Cell_ACDC#21]
**Describe the bug**
When I use the brush tool and release, i get this error.

TypeError: correspondence() got an unexpected keyword argument 'isVisited'
**To Reproduce**
1. Go to frame 14 and use the brush tool on cell #3.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10964296/160504824-661119a5-acf0-4017-8e2e-0745c204b388.png)

**Desktop (please complete the following information):**
 - Python version: 3.9
 - OS: Windows 10
 - Cell-ACDC Version 1.2.4rc8

**Additional context**
https://drive.google.com/file/d/1l-DFUoQ1O67zXmVMojIzuHrbuzFzH5Kq/view?usp=sharing Here are the files for you to reproduce the error
[2022-03-28_16-32-39_gui_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/8366959/2022-03-28_16-32-39_gui_stdout.log)

**Comment by ElpadoCan** [comment]
Oh ok that is a bug with the yeaz tracker that I never use. I will fix it today, in the meantime you can switch back to the acdc tracker (`tracker` menu on the top) thanks!

**Comment by ElpadoCan** [comment]
Ok, I fixed it. Run the command `pip install --upgrade cellacdc` and let me know if it works, thanks!

**Comment by jacobmhkim** [comment]
It works! Thanks!
