### ISSUE TITLE
Converting .tif to segm.npz: UnboundLocal Error

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#22]
**Describe the bug**
Conversion of segmentation mask file in .tif format to segm.npz not working, under Utilities menu.

**To Reproduce**
1. Move .tif file containing segmentation masks to the Images folder under the relevant position, within the ACDC file structure.
2. Open "tif to npz" open in Utilities menu.
3. Select folder and menu options, following popup instructions.
4. Hit OK after "appended text" option.
5. Get error below in terminal, and no .npz file.

Error text: (including preceding two lines)
"Loading data...
Converting .tif to .npz started...
Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\__main__.py", line 307, in launchConvertFormatUtil
    self.convertWin.main()
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\utils\convert.py", line 217, in main
    self.convert(
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\utils\convert.py", line 243, in convert
    np.savez_compressed(newPath, data)
UnboundLocalError: local variable 'data' referenced before assignment"

**Desktop (please complete the following information):**
 - Python 3.9.7
 - OS: Windows 10
 - Cell-ACDC v1.2.4rc10

**Additional context:**
I'm currently attempting to use an old segmentation mask file obtained via the YeaZ GUI in the ACDC GUI, to save the work of re-segmenting. The old file exists in both .tif and .h5 formats. Once I'm able to convert the .tif to a .npz, I was also wondering whether there will be issues with the "aligned" images, since the old mask file was obtained in an interface that doesn't correct for stage drift. Will the align_shift.npy be applied automatically or should I use the un-aligned images instead? If the latter, where do I toggle whether to use the aligned or unaligned version of a position in the ACDC GUI?

**Comment by jordanyx** [comment]
If it helps, here are the links to the tif and h5 files for the thing I was trying to convert:
https://drive.google.com/file/d/1tzlcz71Upaz7CVZzA3ZPHByaGmOxpezA/view?usp=sharing
https://drive.google.com/file/d/1EmZxw6WLttfnEsXqYWww1h_FCvMsTdqb/view?usp=sharing

**Comment by ElpadoCan** [comment]
Thanks Jordan! I'm almost done, I will release soon!

**Comment by ElpadoCan** [comment]
Hi Jordan, I have released `v1.2.4rc11`. Update with `pip install --upgrade cellacdc`. 

I have debugged the conversion to .npz utility and added a new utility for converting from .h5 to .npz

Note that if you want the .npz to be visible to Cell-ACDC it needs to have the same basename as all other files and it needs to have the word `segm` somewhere after `basename_`, e.g., if you have a `pos1_phase.tif`, then the segmentation file should be named `pos2_segm.npz`. This is why you will be asked to append a text at the end of the file during the conversion process. 

For the alignment instead, the `align_shift.npy` will not be applied automatically. For this reason, I added a new utility called `Align or revert alignment...`. This will allow you to select a file and apply the alignment saved in the `align_shift.npy` file.

As an example, let's suppose you want to convert the file `pos2.h5`. Place this file in the `Position_2/Images` folder, where you have all other files, for example `pos2_phase.tif`. You then convert to `segm.npz` by appending `segm` when asked. Then you run the alignment utility and you append the text `aligned`. You will end up with two files, one called `pos2_segm.npz` not aligned and one `pos2_segm_aligned.npz`. This way Cell-ACDC will detect two segmentation masks and it will ask you which one you want to load.

I hope it's clear and let me know if it works, thanks!

**Comment by jordanyx** [comment]
Hi Francesco, perhaps a dumb question--I've tried the usual "pip install --upgrade cellacdc" command but for some reason I'm not getting rc11, it's still on rc10. Any ideas why this might be?

**Comment by ElpadoCan** [comment]
You are right, something went wrong with the upload. I will check it, sorry about that

**Comment by ElpadoCan** [comment]
Ok, it should be uploaded now, let me know if it works, thanks! Sorry again

**Comment by jordanyx** [comment]
Hi Francesco, the converter and alignment utilities both work perfectly now! Thanks a ton, this is a huge help for comparing with older data!
