### ISSUE TITLE
YeastMate Installation on Windows Fails 

### ISSUE THREAD

**Issue by AP712** [SchmollerLab/Cell_ACDC#221]
### Description:

Hi Francesco,
I have a problem with installing YeastMate on a Windows PC. The installation starts automatically through the segmentation module, but after a few errors during the detectron2 installation the process just hangs, and I can only abort the segmentation routine. I have installed the Windows Virtual Studio components following the instructions CellACDC displays in case of a failed YeastMate installation, but this doesn't seem to resolve the issue. 
The last entry on the segmentation log file is "installing YeastMate".
I have attached the full terminal output here as a text file, since it is too long for the respective field.

Thanks a lot for your time and help!
Anastasia Petropoulou

[Terminal Output.txt](https://github.com/SchmollerLab/Cell_ACDC/files/10176093/Terminal.Output.txt)

### Way to reproduce:

Automatic installation of YeastMate through the Segmentation module

### Version information:

```Shell
3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
Cell-ACDC version: 1.2.4rc55
```

**Comment by ElpadoCan** [comment]
This yeastmate github page https://github.com/hoerlteam/YeastMate/issues

**Comment by AP712** [comment]
Hi Francesco,
thanks so much for the quick reply! 
I think at some point I tried the manual installation and indeed it failed again. 
I wanted to try YeastMate as well to have an idea how that works, but I can do that on my personal MacBook. YeaZ will work just fine in general, I just thought I'd ask in case there was something obvious I was missing with the Windows installation. 

I will at some point ask at the YeastMate page and could update you if they offer a solution.

Anyway, thank you again, have a nice evening!

Anastasia

**Comment by ElpadoCan** [comment]
Ok great, on macOS installation should be flawless. Let me know how it goes, thanks! 

Cheers,
Francesco
