### ISSUE TITLE
"Select objects to keep" results in a critical error

### ISSUE THREAD

**Issue by faultby** [SchmollerLab/Cell_ACDC#257]
### Description:

I am working with a segmented movie, and I am going frame by frame to correct the masks. The cells are dividing throughout the movie, but I am only interested to keep masks for some of them, but not the others. Therefore, I am trying to use "Select objects to keep" feature of the segmentation and tracking module. However, after I select several of the objects and press enter, it results in a critical error. 
[2023-01-31_15-32-12_gui_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/10547700/2023-01-31_15-32-12_gui_stdout.log)

### Way to reproduce:

- Segment a movie
- Go to a frame where there are multiple objects
- Switch the "Select objects to keep" toggle on
- Select some of the object present in the frame
- Press "Enter"

### Terminal output:

```Shell
Traceback (most recent call last):
  File "C:\Users\adamenikan\Anaconda3\envs\acdc\lib\site-packages\cellacdc\__init__.py", line 102, in inner_function
    result = func(self, *args)
  File "C:\Users\adamenikan\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 10066, in keyPressEvent
    self.keepIDsConfirmAction.click()
AttributeError: 'QAction' object has no attribute 'click'
```

### Version information:

```Shell
3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)]
Windows-10-10.0.19045-SP0
Cell-ACDC version: 1.2.4rc53
```

**Comment by ElpadoCan** [comment]
Hi Aliaksandr, 

You are absolutely right, thank you very much for reporting this! 

As a temporary solution while I fix this, instead of pressing "Enter", you can click with the mouse on the green tick button on the top-left of the window, beside the list of kept IDs (see screenshot below). Let me know if it works, thanks! 

Cheers,
Francesco

![image](https://user-images.githubusercontent.com/55240925/215806206-277b8a68-f81a-4c6d-a5ca-a5b3df79dc13.png)

**Comment by faultby** [comment]
Dear Francesco,

Yeah, the green tick method works. Thank you!

Best
Alex

**Comment by ElpadoCan** [comment]
Hi Aliaksandr,

I just released `v1.2.4rc62` with a fix for this issue. This version also has a bug fix for computing numerical features of more than two channels. If you need to do that make sure you update to the latest version first.

To update, activate the `acdc` environment and then run the command `pip install --upgrade cellacdc`. Let me know if it works, thanks! 

Cheers,
Francesco

**Comment by faultby** [comment]
Hi Francesco,

It seems to work now, thank you!

Best
Alex

**Comment by ElpadoCan** [comment]
Great, happy to hear that!
