### ISSUE TITLE
Error in function repeatSegm

### ISSUE THREAD

**Issue by ArohiKhurana** [SchmollerLab/Cell_ACDC#265]
### Description:

Error in cell pose segmentation in 3D, both in the segmentation module and in the GUI. 

[2023-02-09_17-05-47_gui_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/10699114/2023-02-09_17-05-47_gui_stdout.log)

### Version information:
v1.2.4
_No response_

**Comment by ElpadoCan** [comment]
Oh yeah that's a bug, thanks for reporting this I will fix it soon!

**Comment by ElpadoCan** [comment]
Hi Arohi, I just fixed this. Please pull the last version and let me know if it works, thanks!

**Comment by ArohiKhurana** [comment]
It's fixed now. Thanks :)
