### ISSUE TITLE
Additional annotation option: number of z-slices per object

### ISSUE THREAD

**Issue by ElpadoCan** [SchmollerLab/Cell_ACDC#276]
### Description:

Add additional annotation option that display the number of z-slices in brackets beside the ID annotation

**Comment by ElpadoCan** [comment]
Implemented on developer version, but not released yet

**Comment by ArohiKhurana** [comment]
Hi Francesco,
This feature works flawlessly. Thanks for adding it, it'll definitely save a lot of time for my analysis.

**Comment by ElpadoCan** [comment]
Closing this because the feature has been released with `v1.2.6`
