### ISSUE TITLE
Data Structure Creation for Multiple-Position File Mixes Up Frames

### ISSUE THREAD

**Issue by AP712** [SchmollerLab/Cell_ACDC#286]
### Description:

Hi Francesco,
I have a weird issue with the data structure creation module. My experiments are done using a Nikon microscope, which outputs NIS Elements files (.nd2). Usually I have multiple positions for each time lapse experiment, which I would so far split into single points, then process with ACDC as instructed. Since the option exists to create data structures for files with multiple positions, I tried that, but have the following problem:

The module runs without problems, the number of positions and frames are recognised correctly, and all positions get processed. However, when opening one position in the data prep module, instead of the expected Position 1 - T1, T2, T3 etc (frames of the time lapse), I get P1-T1, P2-T1, P3-T1 etc., with a total number of frames equal to the correct number of them.
This happens on both Windows and Apple systems, with the latest software installed.

Any idea what is going wrong?

Thanks a lot for your help!
Anastasia

**Comment by AP712** [comment]
Hi Francesco,
thanks for the quick reply. Exactly, instead of the sequence of frames for each position, I get as a second frame the first one of the second position and so on.

I use the "Single microscopy file with one or more positions" option, always working with a single .nd2 file contained alone in a folder to create the data structure. When this file contains only one position (after splitting the multipoints in NIS), the ztc order works perfectly fine. 

I tested all combinations for the order of dimensions, unfortunately none seem to work for the multipoint file... 
My smallest multipoint file is 8GB, it should work with Google Drive. I will send it to you so that you can have a look.

Best,
Anastasia

**Comment by ElpadoCan** [comment]
Yes please, if you can send me the file that will be the fastest for me to check this issue, thanks! 

Best,
Francesco

**Comment by ElpadoCan** [comment]
I have some good news. Updating to the latest Bioformats version 6.12.0 (released on the 14th of February 2023, see [here](https://www.openmicroscopy.org/2023/02/14/bio-formats-6-12-0.html)) solved this issue! 

I still have to release the upgrade yet, but I will do it soon. I will keep you updated thank you for your patience! 

Best,
Francesco

**Comment by ElpadoCan** [comment]
HI Anastasia, I released Cell-ACDC `v1.2.7` with the latest Bioformats that should fix this issue.

To update, activate the `acdc` environment and then run the command `pip install --upgrade cellacdc`.

Let me know if it works and have a good evening! 

Best,
Francesco

**Comment by AP712** [comment]
Hi Francesco,
That was really impressive, thank you so much for all the information and fix! I will update my computers and test it out first thing in the morning. I will close this issue then.

Have a nice evening!
Anastasia
