### ISSUE TITLE
Is it possible to export image with segmentation mask to Fiji?

### ISSUE THREAD

**Issue by carolynw898** [SchmollerLab/Cell_ACDC#333]
### Description:

Hi! Thanks for making such a useful tool, I'm enjoying working with it :)

Just wondering if it's possible to export my image with the segmentation mask to Fiji? I have saved the result from using ACDC to a tiff file but when I try to open it in Fiji I can't see the segmentation mask. Please let me know if it's possible to do this currently! Thank you so much again!

**Comment by ElpadoCan** [comment]
Hi @carolynw898, I'm very happy to hear you like Cell-ACDC! Enjoying doing image analysis is always a good sign 😎.

Anyway, absolutely, you can export for ImageJ. Just go the `Utilities --> Convert file formats --> Convert _segm.npz(s) to ImageJ ROIs` menu on the top menubar of the little launcher you get when you start Cell-ACDC. You will be guided into the selection of the segmentation files and it will then create a `.zip` file containing the Fiji-compatible ROIs.

Let me know if it works, thanks! 

Best,
Francesco

**Comment by carolynw898** [comment]
Hi Francesco,

Thank you so much for the guidance & I was able to export the ROIs successfully! Hope you have an amazing rest of your week!

Carolyn
