### ISSUE TITLE
Option to turn off "missing cell" yellow border, or at least shrink font size

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#35]
Sometimes I'm trying to draw in a small cell mask, but the yellow contour and missing cell ID get in the way. It automatically turns off when I use Brush over it, but not when erasing, and it just gets in the way sometimes. It'd be nice if there was an option to shut it off or shrink the font size when desired.

**Comment by ElpadoCan** [comment]
I released `v1.2.4rc16` which has a fix for this issue. Activate the environment and update with `pip install --upgrade cellacdc`

Now, also the eraser will turn off annotations when is hovering them. Additionally, you can hide all annotations (but keep the overlaid masks to see what you are erasing) by double-press on the spacebar. If you double press it again, all annotations will be back.

Let me know if it works, thanks!

**Comment by jordanyx** [comment]
The double spacebar thing works great! I will note that hovering over the number doesn't seem to work, only over the yellow contour, so that's not optimal, but the spacebar trick is more than enough. Definitely consider noting this feature somewhere for new users!

**Comment by ElpadoCan** [comment]
Happy to hear that you like the trick! 

The double spacebar is one of those few functions that do not have a button, so they are less easy to find. You can find a list of these functions from the `Help --> Trips and Tricks` menu on the top menubar. However, the double spacebar trick is not there, I forgot to add it :D. I will add it in the next release. 

We will also need a few pop-ups with tips and tricks for new users (that can be turned off, of course), especially for the hidden functions.

Another "hidden" function is the font size. You can change it from the `Edit --> Font size` menu on the top menubar.

For the hovering thing, it works only when you hover on the segmentation mask of the cell (so yes, inside the contours). Typically the number is all inside the contour, so I'm guessing you are talking of small cells for which the number is larger than the cell? In that case, I am not sure I can detect the footprint of the number, I have to look into it, thanks for suggesting that!
