### ISSUE TITLE
Error when trying to reassign mask ID

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#37]
**Describe the bug**
Sometimes when trying to use the ID reassign tool, I get an error that I can't seem to reproduce consistently unfortunately.

**To Reproduce** (not especially consistent)
1. Use reassign ID tool in seg/track mode.
2. Click on cell, type in new ID and hit enter.
3. Get popup window: "Error in function gui_mousePressEventImg2", accompanied by below error:
Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 122, in inner_function
    result = func(self, *args)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 3156, in gui_mousePressEventImg2
    doNotShowAgain) = self.propagateChange(
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 7269, in propagateChange
    return UndoFutFrames, applyFutFrames, endFrame_i, doNotShowAgain
UnboundLocalError: local variable 'doNotShowAgain' referenced before assignment

I can usually get around the error by going back a frame, then going forward and trying again; not sure why this works.

**Desktop (please complete the following information):**
 - Python 3.9.7
 - OS: Windows 10
 - Cell-ACDC v1.2.4rc15

**Comment by jordanyx** [comment]
Hi Francesco,

I had the error happen exactly once since then, so the frequency is drastically reduced compared to before! Still not sure what causes it, but it did happen once just now.

**Comment by ElpadoCan** [comment]
Interesting, if it happens again can you paste the exact error here? Because it might be slightly different now, thanks!
