### ISSUE TITLE
Add "frames in cell cycle" data

### ISSUE THREAD

**Issue by jacobmhkim** [SchmollerLab/Cell_ACDC#38]
**Is your feature request related to a problem? Please describe.**
Right now, we can align the full cell cycle data to the budding event, but not to birth or mitosis. 

**Describe the solution you'd like**
Add columns in the dataframe for "frames in cell cycle" and "cell cycle length".

**Describe alternatives you've considered**

**Additional context**
Thank you!

**Comment by Beno71** [comment]
Hi Jacob,
for the cell cycle phase length, there is already the column "phase_length" calculated in the notebook. There's some more general stats about the current cell cycle phase like phase_begin and phase_end and for the sake of completeness I added the calculation of the column "time_in_phase" in the notebook as well. When you now filter for G1 cells, you can align at birth/mitosis (time_in_phase=0, phase=G1 and complete_phase=1) and analyse the data until the next G1/S transition.

Now I hope I understood correctly, that you want to take a more zoomed out view on the whole cell cycle from birth to G1/S transition and further on to the next mitosis of the current cell. For that, I added a line to calculate "time_in_cell_cycle" which counts the number of frames, from when the observed cell increases its replicative age (=generation_num) by 1.
I recommend **filtering for complete cell cycles (complete_cycle==1)**. For cell cycles with unknown start, the calculated data is pretty much meaningless.

I push the changes now. Hope that helps! Fell free to reach out if you have any questions.

**Comment by jordanyx** [comment]
Hi Francesco, thanks for adding this parameter!

I was wondering if you know what would be the easiest way to get something like "phase_length" but for the whole cell cycle length? E.g. I want to plot the distribution of overall cell cycle lengths.

**Comment by Beno71** [comment]
Hi Jordan,
I added those lines of code to the notebook:
`complete_cc_data = overall_df_with_rel[overall_df_with_rel.complete_cycle==1]
cc_lengths = complete_cc_data.groupby(['Cell_ID', 'generation_num', 'file', 'position'])['time_in_cell_cycle'].max()
sns.histplot(cc_lengths)
plt.show()`
First, I filter for complete cell cycles.
Then I group by cell, generation, file and position which is equivalent to filter "by cell cycles".
Aggregating max of the recently added column 'time_in_cell_cycle' yields exactly what you describe in your comment (I hope).
Let me know, if this helps!
Beno

**Comment by jordanyx** [comment]
This does the job, thanks Beno! I think I need to learn how to use groupby properly haha.

**Comment by Beno71** [comment]
Great! Then I'll close this one.
