### ISSUE TITLE
btrack for Cell_ACDC

### ISSUE THREAD

**Issue by Ciro1990** [SchmollerLab/Cell_ACDC#4]
Hi there! 

First of all, thanks for developing such great tool! I would like to request a new feature for the software.
Is it possible to add a new tracker to the interface? In particular, I would like to use bTrack (https://github.com/quantumjot/BayesianTracker) on Cell_ACDC. 

It would be great if you could add it!

Thanks in advance!
Ciro

**Comment by ElpadoCan** [comment]
Hi @Ciro1990 , that looks pretty straightforward to add, I will implement it soon! I'll keep you updated!

**Comment by ElpadoCan** [comment]
Implemented in v1.2.4
