### ISSUE TITLE
GUI left image doesn't update after using eraser tool

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#42]
**To Reproduce**
1. Load image
2. Use eraser tool to erase something
3. Use arrow keys or scroll bar to attempt to change frames
4. Right image updates, but masks for left one don't until I use the brush tool again to paint something, or click a second time with the eraser. IDs do appear to update and change position (see included image). No errors are returned at any point.

**Screenshots**
![error](https://user-images.githubusercontent.com/99368623/168458086-880dbab5-37a8-4d05-883c-d70e43f8b3b8.PNG)

**Desktop (please complete the following information):**
 - Python version: 3.9.6
 - OS: Windows 10
 - Cell-ACDC v1.2.4rc20

**Comment by ElpadoCan** [comment]
Hi Jordan, you are right, essentially it updates only when you deactivate the eraser. I accidentally added this when we changed the eraser behaviour to always show the overlaid segmentation masks. Essentially with the eraser active it still thinks it needs to show whatever image you had before activating the eraser. Of course this needs to be reinitialised when changing frame. Thanks for spotting that I will fix it today.

**Comment by ElpadoCan** [comment]
Hi Jordan, I released `v1.2.4rc22` which has a fix for this issue. Let me know if it works, thanks!

**Comment by jordanyx** [comment]
Wow that was fast! Yes, it seems like it's back to normal now. Thanks Francesco!
