### ISSUE TITLE
Repeat segmentation on a range of frames only

### ISSUE THREAD

**Issue by Ciro1990** [SchmollerLab/Cell_ACDC#46]
Hi Francesco,

first thing first, thanks for developing such a great tool! I am enjoying using it!

I was wondering if it is possible to add a feature for the segmentation on the GUI. In particular, I would find extremely useful to have the possibility to repeat the segmentation on a specific range of frames only. 

Thanks a lot!
Ciro

**Comment by ElpadoCan** [comment]
Hi Ciro, I added the feature you requested in the latest developer version. Update with `git pull` and let me know if it works. You can find the new feature in the `Segment --> Segment multiple frames` menu on the top of the GUI. Cheers
