### ISSUE TITLE
Resaving GUI output on multiple positions

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#48]
Sometimes I add a custom metric to the ACDC list of outputs, and having to manually re-open previously analyzed experiments and save just to get a single metric in every file is somewhat tedious. It would be nice if there was some way to automatically load and re-save measurements for multiple files at a time. Thanks!

**Comment by ElpadoCan** [comment]
Sure, I will make an utility to resave the some or all the metrics of one or more positions, good idea.

**Comment by ElpadoCan** [comment]
Hi Jordan, I released `v1.2.4rc25` with a new utility. From the main launcher select the menu `Utilities` from the top menu bar and then select the `Compute measurements for one or more experiments...` utility. Follow the pop-up dialogues to choose one or more experiments and the position folders. It will then recalculate all the selected metrics for all the selected experiments. Let me know if it works, thanks!

**Comment by jordanyx** [comment]
Great, will do!

**Comment by jordanyx** [comment]
Hi Francesco, I've finally gotten around to testing this but ran into the following error after choosing folders and positions:

------------------------------
Processing experiment n. 1/2, Position n. 1/4
Processing experiment n. 1/2, Position n. 2/4
Processing experiment n. 1/2, Position n. 3/4
Processing experiment n. 1/2, Position n. 4/4
====================
Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\utils\compute.py", line 233, in workerCritical
    raise error
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 26, in run
    func(self)
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\workers.py", line 208, in run
    posData.loadOtherFiles(
TypeError: loadOtherFiles() got an unexpected keyword argument 'endFilenameSegm'

**Comment by jacobmhkim** [comment]
I also get the same error

**Comment by jacobmhkim** [comment]
Hi Francesco. Could we get an update on when this buf will be fixed? I understand if you are busy. I just want to know so that I can plan to manually save the data if this fix will take a while. Thanks!

**Comment by ElpadoCan** [comment]
Hi Jacob, I will release soon, probably tomorrow or Wednesday, is that OK? Thank you for your patience

**Comment by jacobmhkim** [comment]
Thank you so much! I will wait patiently

**Comment by ElpadoCan** [comment]
Hi Jordan and Jacob,

I just released `v1.2.4-rc31` which has a fix for this issue. Please install with `pip install --upgrade cellacdc` and let me know if it works, thanks!

**Comment by ElpadoCan** [comment]
Please wait to test this release since I am not sure whether the computation through the utility is deleting cell cycle annotations or not. 

I am testing now. I will keep you updated.

In any case, please backup the `acdc_output.csv` file before trying, just to be sure.

**Comment by jordanyx** [comment]
I think it's working great now, thanks!
