### ISSUE TITLE
Improve handling of data-prep ROIs

### ISSUE THREAD

**Issue by ElpadoCan** [SchmollerLab/Cell_ACDC#489]
### Description:

Improvements on the prompt below:

- [x] Do not ask if data is cropped and ignore existing ROI even if smaller than crop
- [x] Ask what to do with existing ROI smaller than image (if not cropped)
- [x] Inform that one can segment a ROI smaller than image when info is not present (in case they did not know)

**Comment by Beno71** [comment]
In third point "when info is not present" meaning that no crop was performed and no ROI selected in dataprep right?

**Comment by ElpadoCan** [comment]
Yes, it would mean data prep was skipped

**Comment by ElpadoCan** [comment]
These are the new prompts:

> Do not ask if data is cropped and ignore existing ROI even if smaller than crop

![image](https://github.com/SchmollerLab/Cell_ACDC/assets/55240925/45acdcfd-2b2d-44d1-b6d8-accb7f76c3c6)

> Ask what to do with existing ROI smaller than image (if not cropped)

![image](https://github.com/SchmollerLab/Cell_ACDC/assets/55240925/3f5e3e1b-82f7-44da-b3ec-5debfeadf48e)
