### ISSUE TITLE
Cell cycle analysis problems with cells of unknown history

### ISSUE THREAD

**Issue by jacobmhkim** [SchmollerLab/Cell_ACDC#49]
**Describe the bug**
When a cell flows into the field of view, ACDC has issues with assigning the cell cycle phase. For example, when a new G1 cell appears, it's automatically assigned as a bud. I use the Annotate Unknown History tool on that cell, and it turns into a G1 cell. But when that G1 cell forms a bud, and I try to assign that bud to the correct mother, I get a critical error.

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/10964296/168910699-67a82c6f-536a-47d7-962c-c37559292597.png)

**Desktop (please complete the following information):**
 - Python version: 3.9
 - OS: Windows 10
 - Cell-ACDC Version  v1.2.23

**Additional context**
[2022-05-17_10-26-32_gui_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/8711567/2022-05-17_10-26-32_gui_stdout.log)
https://drive.google.com/file/d/1kuOGFTkgjOQDjM1n3Ob27V9IzBy_Eo55/view?usp=sharing example movie of problem

**Comment by ElpadoCan** [comment]
Hi Jacob, thank you very much for the details in reporting this bug, it really helped a lot because I could fix it in no time.

So, I released `v1.2.4rc24` which has the fix for this issue. Update with `pip install --upgrade pip` and let me know if it works, thanks!

**Comment by jacobmhkim** [comment]
thanks! It works
