### ISSUE TITLE
Error in function `gui_mouseReleaseEventImg1` v1.4.27

### ISSUE THREAD

**Issue by Akankshazmaze** [SchmollerLab/Cell_ACDC#509]
### Description:

Application keeps showing error after a few button click (uses). Then says to restart to use the application. This issue has persisted since v1.4.16.
[.2024-04-18_15-26-34_acdc_gui_969f6c97-a4f6-49ba-b1a8-ca9ef0dd40e8_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/15023177/default.2024-04-18_15-26-34_acdc_gui_969f6c97-a4f6-49ba-b1a8-ca9ef0dd40e8_stdout.log)

### Terminal output:
```
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\acdc\lib\site-packages\cellacdc\__init__.py", line 386, in inner_function
    result = func(self, *args)
  File "C:\ProgramData\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 6584, in gui_mouseReleaseEventImg1
    self.trackManuallyAddedObject(posData.brushID, self.isNewID)
  File "C:\ProgramData\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 21825, in trackManuallyAddedObject
    trackedID = tracked_lab[mask][0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

### Version information:

v1.4.27

**Comment by ElpadoCan** [comment]
Hi @Akankshazmaze,

Unfortunately I cannot replicate the error, so I will need more information. Can you tell me the steps you do to trigger the error? Do you start with and empty segmentation file on timelapse data? Does this happen when you add a new object with the brush? 

If you can, it would be very helpful to record the steps you do to trigger the error. To do so you can use the software LICEcap that you can download from here https://licecap.en.softonic.com/.

Once installed you can run LICEcap and you will get a window that you can place around Cell-ACDC gui window. Press the Record button and use acdc to trigger the error. Then send here the GIF file generated. Thanks! 

Another option is to zip the position folder and send it to me (you can put it on your cloud of choice and share it to my email padovaf@tcd.ie) with instructions on how to replicate the error. 

Thank you for your patience! 

> So I went to the Position_n/Images folder. Issue is, there is one .npy file for the entire time-lapse data. While I have separate .npy file for each frames.
Is there a way I can combine them all?

Unfortunately there is no feature in Cell-ACDC to combine them, but it's pretty simple to do with a Python script. I can send you one but I need some information. Do you have the files all in a folder without any other file in it? How are the single frame files named? If you send me a screenshot of the File Explorer on the folder where you have the single frame files I can help you writing a very small Python script to combine them. 

> Also in Cell_ACDC, is there a way to manually segment each frame and have the data automatically saved?

Cell-ACDC saves only when you click the Save button. There actually is an autosave function, you can activate it with the Toggle in the bottom-left of the GUI (see screenshot below). However, this function is more for recovery of unsaved data so I recommend that you save yourself by simply pressing `Ctrl+S`. This will only save the segmentation file. 

In case you need to recover from the autosaved data, Cell-ACDC will ask you to recover from there when you load the same Position again. Let me know if it's clear enough, thanks! 

![image](https://github.com/SchmollerLab/Cell_ACDC/assets/55240925/368b7252-441f-4dff-9ec6-463da9004b76)

**Comment by Akankshazmaze** [comment]
So what I do is:
Segment the file using one of the segmentation modules. 
And some some bacteria do not get segmented correctly. Here, I will remove and make correct boundaries using the Brush and Eraser tool in the ACDC_GUI.
After a few actions, the program will show me the error: ACDC.
Autosave segmentation, is working! just worked with this.
The error also shows when I try to use the function: Select object to keep. The error will pop us when I try to save the hgihlighted objects.
Error is as follows:
**File "C:\ProgramData\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 18303, in applyKeepObjects
    self.highlightHoverIDsKeptObj(0, 0, hoverID=0)
  File "C:\ProgramData\anaconda3\envs\acdc\lib\site-packages\cellacdc\gui.py", line 20746, in highlightHoverIDsKeptObj
    objIdx = posData.IDs_idxs[hoverID]
KeyError: 0
====================================
WARNING: Cell-ACDC is in error state. Please, restart.
====================================**
```

**Comment by Akankshazmaze** [comment]
> Unfortunately there is no feature in Cell-ACDC to combine them, but it's pretty simple to do with a Python script. I can send you one but I need some information. Do you have the files all in a folder without any other file in it? How are the single frame files named? If you send me a screenshot of the File Explorer on the folder where you have the single frame files I can help you writing a very small Python script to combine them.

This will be very helpful!
I have segm_npy and the respective image in the same folder. Respective png file of the segm files also present, but they can be deleted.
SS attached
![image](https://github.com/SchmollerLab/Cell_ACDC/assets/77427674/36f9f7c0-b4d5-462a-8e65-60ceb9133537)
Thank you

**Comment by ElpadoCan** [comment]
Ok, I think I fixed the two errors you reported. I did not release a new version because I would like you to test the fixes first. 

To upgrade to the latest version activate the `acdc` environment and run the following command
```
pip install --upgrade "git+https://github.com/SchmollerLab/Cell_ACDC.git"
```

If it complains that the command `git` cannot be found, please close the terminal, install [Git](https://git-scm.com/download/win) (link below) and try the upgrade again. Let me know if the issues are fixed. Once you are happy with it I can release a new version, thanks! 

Git link: https://git-scm.com/download/win

Best,
Francesco

**Comment by ElpadoCan** [comment]
> > Unfortunately there is no feature in Cell-ACDC to combine them, but it's pretty simple to do with a Python script. I can send you one but I need some information. Do you have the files all in a folder without any other file in it? How are the single frame files named? If you send me a screenshot of the File Explorer on the folder where you have the single frame files I can help you writing a very small Python script to combine them.
> 
> This will be very helpful! I have segm_npy and the respective image in the same folder. Respective png file of the segm files also present, but they can be deleted. SS attached ![image](https://private-user-images.githubusercontent.com/77427674/323581771-36f9f7c0-b4d5-462a-8e65-60ceb9133537.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0NDU2NzMsIm5iZiI6MTcxMzQ0NTM3MywicGF0aCI6Ii83NzQyNzY3NC8zMjM1ODE3NzEtMzZmOWY3YzAtYjRkNS00NjJhLThlNjUtNjBjZWI5MTMzNTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDEzMDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNTdmZjdhOGIzZDgzNGMxNmY2ZTdiYWQxYjdmMzIyODdiNDI5NTRkMjUzYThjZGUxYzEwM2Y1YTMzZDkyMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XCNDd3jstSabvbTBPVIArkWfb8l1JVpAHv_B_CAPRIM) Thank you

Are the `p00`, `p01`, etc the individual time points?

**Comment by ElpadoCan** [comment]
Btw, are those `seg.npy` files generated from the cellpose GUI? Because if that's the case, one easier option is to run cellpose from Cell-ACDC. You can also run your custom cellpose model in Cell-ACDC. This way the correct segmentation file is generated by Cell-ACDC.

**Comment by Akankshazmaze** [comment]
> Btw, are those `seg.npy` files generated from the cellpose GUI? Because if that's the case, one easier option is to run cellpose from Cell-ACDC. You can also run your custom cellpose model in Cell-ACDC. This way the correct segmentation file is generated by Cell-ACDC.

Yes, I segmented them using custom model trained in Cellpose. I had to segment them on Cellpose, as ACDC was crashing😅. Now I don't have this crashing issue while segmenting. I'll continue here.


 
> Are the `p00`, `p01`, etc the individual time points?

Yes :)

But I guess, I may not need this as you fixed the crashing issue!

I have another request:
How do I annotate a cell manually with a specific ID given in the previous frame?

**Comment by Akankshazmaze** [comment]
> To upgrade to the latest version activate the `acdc` environment and run the following command
> 
> ```
> pip install --upgrade "git+https://github.com/SchmollerLab/Cell_ACDC.git"
> ```

I was able to install this easily, thanks to your instructions.

However, the manual correction I am making in each frames are not getting saved automatically. When I go back to the last frame, where I made correction, the segments were not the one I made. For eg:
![image](https://github.com/SchmollerLab/Cell_ACDC/assets/77427674/ffeb0202-f813-4af3-9b9f-4e33a57ba39d)
The region highlighted in black has a cell that has been fragmented in 3 parts, I make the correction, move onto to other frames, and when I come back to this frame, the cell is fragmented again.




Another issue with keep objects:
Error in function:applyKeepObjects.
[.2024-04-18_21-27-10_acdc_gui_e45a477c-3515-4e35-af8a-15c96b501e52_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/15027556/default.2024-04-18_21-27-10_acdc_gui_e45a477c-3515-4e35-af8a-15c96b501e52_stdout.log)

**Comment by Akankshazmaze** [comment]
After the new update, if 2 cells overlap, the one of the cell is split in 2 cells.

**Comment by ElpadoCan** [comment]
> I have another request:
How do I annotate a cell manually with a specific ID given in the previous frame?

To change the ID manually there is a button on the top toolbar with this icon [Edit ID icon](https://github.com/SchmollerLab/Cell_ACDC/blob/main/cellacdc/resources/icons/edit-id.svg). Activate that button and then right-click on a cell. You will get an entry box where to type the new ID. Let me know if it works, thanks.

> The region highlighted in black has a cell that has been fragmented in 3 parts, I make the correction, move onto to other frames,

Can you please send me two screenshots of the entire GUI (I also need to see the scrollbars below the image) one after correcting and one after going back to the frame where the correction is not there anymore? Thanks! 

> After the new update, if 2 cells overlap, the one of the cell is split in 2 cells.

I will also need a screenshot here to understand better. 

If you can, it would be much easier if you share the Position folder with me (you can use my email padovaf@tcd.ie). This way I can test the issues as well. Thank you very much! 

Best,
Francesco

**Comment by Akankshazmaze** [comment]
Segmentation issue occuring when using omnipose. I have attached the critical error displayed and the log. The **version used: 1.4.30.dev5+g7d6335c**,
![image](https://github.com/SchmollerLab/Cell_ACDC/assets/77427674/a9384dd7-bfe0-43cf-8f13-1dd26219050a)

[.2024-04-29_15-31-48_main_21eee7e8-1e0b-498e-8e99-455e1bbaf8c0_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/15147708/default.2024-04-29_15-31-48_main_21eee7e8-1e0b-498e-8e99-455e1bbaf8c0_stdout.log)

**Comment by Akankshazmaze** [comment]
> If you can, it would be much easier if you share the Position folder with me (you can use my email [padovaf@tcd.ie](mailto:padovaf@tcd.ie)). This way I can test the issues as well. Thank you very much!

I do not understand what is it that I am doing so wrong. I have shared with you on Google drive the Positions_n folder. Please have a look. Thankyou. Choice of segmentation module: either Omnipose or cellpose 3.0
https://drive.google.com/drive/folders/1_CuJlotiQBh9K1FGQNC7QpSEjdPRSl0Z?usp=drive_link

Thankyou
Akanksha

**Comment by ElpadoCan** [comment]
Hi @Akankshazmaze,

I sent you an invitation to join our Slack workspace for acdc users. It might be much easier to communicate there, thanks! 

Best,
Francesco

**Comment by ElpadoCan** [comment]
Hi @Akankshazmaze, I will close this since it seems that re-installing Cell-ACDC solved it, right? Talk to you on Slack!
