### ISSUE TITLE
An issue with saving a file with additional metrics

### ISSUE THREAD

**Issue by MasaruShimasawa** [SchmollerLab/Cell_ACDC#51]
**Describe the bug**
I can't save a file with additional metrics. This is the error log.
[2022-05-31_14-34-24_gui_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/8809643/2022-05-31_14-34-24_gui_stdout.log)

**To Reproduce**
1. Go to 'launch GUI' on Cell ACDC.
2. Open the following file. 
3. https://drive.google.com/drive/folders/1j6XKH281JlvzhmliNUinKOkRtMX90HeI?usp=sharing
4. Save with additional metrics.
5. See error

**Expected behavior**
You can't save the file and see the error.

**Screenshots**
<img width="1440" alt="スクリーンショット 2022-05-31 午後2 51 14" src="https://user-images.githubusercontent.com/103140487/171290675-bc94fbb1-ad66-46a8-a471-d61b662db157.png">

**Desktop (please complete the following information):**
 - Python version: Python 3.9
 - OS: macOS Monterey 12.4
 - Cell-ACDC Version 1.2.4rc24
**Additional context**

**Comment by MasaruShimasawa** [comment]
Hello, Francesco. Thank you for your handling. I will try removing the files and see if I can save with the metrics. Actually, I didn't do the data prep module for this file, so I will ask the one who did about the possibility.

**Comment by MasaruShimasawa** [comment]
The metrics can be saved with the removal of these aligned_bkgrRoiData.npz files.

**Comment by ElpadoCan** [comment]
Hi Masaru, I released `v1.2.4rc25` where it will not be possible to resize the background ROI to something smaller than 1 pixel. If you don't need the background ROI you can right-click on it and select "Remove ROI".

**Comment by ElpadoCan** [comment]
Hi Masaru, as pointed out in issue #56, the version `rc25` has a bug. I fixed it in the latest release `v1.2.4rc26`. Sorry about that!

Please update with `pip install --upgrade cellacdc`, thanks!
