### ISSUE TITLE
Save model used and parameters of model for segmentation and tracking

### ISSUE THREAD

**Issue by Teranis** [SchmollerLab/Cell_ACDC#543]
### Description:

Saving the model and parameters used to create a segmentation mask to a text file might be useful for reproducing results and keeping track of "good parameters" for the data

**Comment by ElpadoCan** [comment]
Hi @Teranis, this is already implemented in the `cellacdc.load.loadData.saveSegmHyperparams` which is called everytime you segment and it saves the parameters to the file ending with `segm_hyperparams.ini`.

Let me know if that does what you wanted, thanks!
