### ISSUE TITLE
Data prep module: way to know if a position has already been processed

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#55]
A super minor suggestion for quality of life--it would be nice if, when opening a given experiment and selecting positions, the data prep module informed the user which positions were already processed. Sometimes I have many positions I'm going through at once and I lose track of which one I'm on. I can check the folder if it has the right saved files, but it'd be nice if this was built into the GUI, the same way that the main GUI module lets you know which positions you've done cell cycle analysis on for instance.

**Comment by ElpadoCan** [comment]
Hi Jordan, I released `v1.2.4rc26` with the functionality you requested. The list of positions in the data prep will now have an additional text "(already prepped)" like the GUI does. 

Please update with `pip install --upgrade cellacdc` and let me know if it works, thanks!

**Comment by jordanyx** [comment]
Looks like it's working, thank you!
