### ISSUE TITLE
Error in segmentation module

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#59]
I'm getting an error with the segmentation module I haven't had before.

Steps:
1. run data through pipeline as normal up to segmentation module
2. run segmentation module, follow prompts
3. select positions to segment
4. Get error after hitting "ok" (see below)

Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\__main__.py", line 557, in launchSegm
    self.segmWin.main()
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\segm.py", line 681, in main
    hyperparams['segm_channel_name'] = user_ch_name
UnboundLocalError: local variable 'user_ch_name' referenced before assignment

I noticed that I didn't get the prompt to choose "Phase" as the channel go segment on, so maybe something's getting called out of order?

Windows 10, Python 3.9.6,  ACDC v1.2.4rc26

**Comment by ElpadoCan** [comment]
Hi Jordan, if you have only one channel it doesn't ask you to select it, it uses the only channel present. 

However, unfortunately, I cannot replicate with one of my datasets, could you please share a Position folder with me? My Google Drive email is padovaf@tcd.ie 

Just to be sure, could you also send me the log file of that session? It would be a file ending with `segm_stdout.log` in the `.acdc-logs` folder in your user path. 

Thanks!

**Comment by jordanyx** [comment]
Hi Francesco, here's the data: https://drive.google.com/file/d/1i_49Uf6dseaLL8fNdcFRHy4gF6tnknYP/view?usp=sharing

I'll send over the log file as soon as I'm back at my work computer. For now, I can say that it's a 3-channel movie, and for some reason the exact same data was able to be segmented fine on someone else's machine that was still on ACDC rc24.

**Comment by ElpadoCan** [comment]
Ok, thanks! Can you try to update to `v1.2.4rc28` in the meantime? I fixed a small bug (that could be correlated to your issue) for another user yesterday and released a new version. Please update with `pip install --upgrade cellacdc`. Let me know if it works, thanks!

**Comment by ElpadoCan** [comment]
Hi Jordan, I can confirm that this should be fixed in `v1.2.4rc28`. Let me know it that's true, thanks!
