### ISSUE TITLE
Error while loading data

### ISSUE THREAD

**Issue by lostinwild** [SchmollerLab/Cell_ACDC#72]
Hi,
I am unable to load TIF images, i get "IndexError: list index out of range" error. Please find the log file attached...would really appreciate your help

[2022-06-29_13-27-56_gui_stdout.log](https://github.com/SchmollerLab/Cell_ACDC/files/9008452/2022-06-29_13-27-56_gui_stdout.log)

**Comment by ElpadoCan** [comment]
Hi @lostinwild I'm sorry to hear you are having issues, but we'll fix them.

As far as I can see from the log file you did not create the files with the module `0. Create data structure from microscopy file(s)...`, right?

Could you please send me a screenshot of the files you have inside the `C:/Users/gaurav/Desktop\20220629_132811_acdc\Images` folder? You can paste the screenshot in a reply to this message or you can drag and drop the screenshot file. 

The fastest way for me to debug would be to have that folder, but I totally understand if you cannot share the data. 

In case you can share, could you please share it with my google drive account padovaf@tcd.ie ? If you have any other way to send me the files is also fine of course. Thanks!

**Comment by ElpadoCan** [comment]
One quick thing you can try before sharing the data is to put the `C:/Users/gaurav/Desktop\20220629_132811_acdc\Images` folder inside a Position folder. Cell-ACDC requires data to be structured into Position folders. 

Try to put the `Images `folder inside a folder called `Position_1` so that the path `C:/Users/gaurav/Desktop\20220629_132811_acdc\Images` becomes ``C:/Users/gaurav/Desktop\20220629_132811_acdc\Position_1\Images``

Let me know if that works, thanks!

**Comment by ElpadoCan** [comment]
I did some tests, and from your log file, it appears to me that you used the `File --> Open image/video file` function, am I right?

If that's the case I just found out now that this function is broken. I basically never use it so I never found this bug. I will fix it in the next release, sorry about that.

In the meantime, please use the `File --> Load folder` action (or the button on the top toolbar with the folder icon) and, when prompted, select the `Images` folder. Note that having the `Images` folder inside a Position folder is still required. 

Let me know if that works, thanks!

**Comment by lostinwild** [comment]
Thanks for addressing the issue so promptly. I feel this program will be a game-changer and has the real potential of becoming the standard image-processing tool specially for yeast. 
I would suggest you to upload a hands on you-tube tutorial soon that would tremendously increase the reach to the imageJ crowd as well

**Comment by ElpadoCan** [comment]
I'm happy to hear your issue is solved and that you like Celll-ACDC! Do not hesitate to contact us with any issues and/or ideas on how to improve the software!

I agree, we need more tutorials and we are working on it, so stay tuned! 

Cheers,
Francesco
