### ISSUE TITLE
Failure to install javabridge on Windows

### ISSUE THREAD

**Issue by jordanyx** [SchmollerLab/Cell_ACDC#9]
**Describe the bug**
Failure to install javabridge on Windows.

**To Reproduce**
1. Install and open CellACDC v1.2.4 as described on Github.
2. Open "Create data structure from microscopy file(s)..." option in the GUI.
3. Click "ok" on the popup window that offers to install Javabridge.

**Expected behavior**
I thought this would enable successful installation of javabridge, but I get the following error:
Traceback (most recent call last):
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\cellacdc\dataStruct.py", line 801, in __init__
    import javabridge
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\javabridge\__init__.py", line 38, in <module>
    from .jutil import start_vm, kill_vm, vm, activate_awt, deactivate_awt
  File "C:\Users\jyxiao\Anaconda3\envs\acdc\lib\site-packages\javabridge\jutil.py", line 162, in <module>
    import javabridge._javabridge as _javabridge
  File "_javabridge.pyx", line 1, in init _javabridge
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Desktop (please complete the following information):**
 - OS: Windows 10
 - CellACDC v1.2.4, installed and opened using Anaconda prompt

**Comment by jordanyx** [comment]
Whoops! I ignored it at first because it was for Mac, but I'm going to try the solution in the other thread first.

**Comment by ElpadoCan** [comment]
Hi Jordan,

I had that same error on another PC and the fix is different from macOS. The difference is that a UNIX system already has a C++ compiler installed, while Windows does not. 

Anyway, I created a new issue with instructions on how to install javabride on Windows, see issue #10 

Let me know if it works. I close this issue and you can comment and write on the other one.
